version: '3'

services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build: ./client
    ports:
      - "8080:80"
    volumes:
      - ./client:/usr/share/nginx/html
    restart: always
